apiVersion: v1
kind: Service
metadata:
  name: ubuntu-obs
spec:
  type: ClusterIP
  ports:
    - name: ubuntu-prom
      port: 9090
      targetPort: 9090
    - name: ubuntu-graf
      port: 3000
      targetPort: 3000
    - name: node-exporter
      port: 9100
      targetPort: 9100    
  selector:
    app: ubuntu-obs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-obs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-obs
  template:
    metadata:
      labels:
        app: ubuntu-obs
    spec:
      containers:
      - image: brainupgrade/ubuntu-obs
        name: ubuntu-obs
        resources: 
          limits:
            cpu: 1000m
            memory: 2048Mi
          requests:
            cpu: 500m
            memory: 1024Mi         
        ports:
        - containerPort: 9090
          name: ubuntu-prom
        - containerPort: 3000
          name: ubuntu-graf        