apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: obs-springboot
    release: prometheus
  name: obs-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obs-springboot
      release: prometheus
  template:
    metadata:
      labels:
        app: obs-springboot
        release: prometheus
    spec:
      containers:
      - image: brainupgrade/observability-springboot:latest
      # - image: ghcr.io/blueswen/spring-boot-observability/app:latest
        name: obs-springboot
        resources:
          limits:
            cpu: 1000m
            memory: 2048Mi
          requests:
            cpu: 500m
            memory: 1024Mi
        env:
        - name: server.port
          value: "8080"
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace          
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: spring.application.name
          value: "$(MY_NAMESPACE)-$(POD_NAME)" 
        - name: environment
          value: "production"
        - name: TARGET_ONE_HOST
          value: obs-springboot
        - name: TARGET_TWO_HOST
          value: obs-springboot
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://tempo:4317"
        - name: OTEL_SERVICE_NAME
          value: "$(POD_NAME)"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "pod=$(POD_NAME)"
        - name: OTEL_METRICS_EXPORTER
          value: "none"
        - name: management.endpoints.web.exposure.include
          value: "*"
        - name: management.metrics.distribution.percentile-histogram.http.server.requests
          value: "true"
        - name: management.metrics.web.server.request.autotime.enabled
          value: "true"
        - name: management.metrics.tags.application
          value: "$(MY_NAMESPACE)-$(POD_NAME)"     
        - name: spring.rabbitmq.host
          value: rabbitmq
        - name: spring.redis.host
          value: "redis"
        - name: spring.redis.port
          value: "6379"
        - name: spring.datasource.url
          value: "jdbc:postgresql://postgres:5432/postgres"
        - name: spring.datasource.username
          value: "postgres"
        - name: spring.datasource.password
          value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: obs-springboot
  labels:
    app: obs-springboot
    release: prometheus
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'
    prometheus.io/path: '/actuator/prometheus'
spec:
  type: NodePort
  ports:
  - name: metrics
    port: 80
    targetPort: 8080
  - name: call
    port: 8080
    targetPort: 8080
  selector:
    app: obs-springboot
    release: prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    release: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      release: prometheus
  template:
    metadata:
      labels:
        app: postgres
        release: prometheus
    spec:
      containers:
        - name: postgres
          image: postgres:16.2
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "postgres"
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
        - name: postgres-exporter
          image: prometheuscommunity/postgres-exporter:latest
          env:
            - name: DATA_SOURCE_URI
              value: "localhost:5432/postgres?sslmode=disable"
            - name: DATA_SOURCE_USER
              value: "postgres"
            - name: DATA_SOURCE_PASS
              value: "postgres"
          ports:
            - containerPort: 9187  # Default port for postgres_exporter
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "200m"              
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    release: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      release: prometheus
  template:
    metadata:
      labels:
        app: redis
        release: prometheus
    spec:
      containers:
        - name: redis
          image: redis:7.2.4
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
        - name: redis-exporter
          image: oliver006/redis_exporter:latest  # Redis Exporter for Prometheus
          resources:  
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
          - containerPort: 9121
          args:
          - "--redis.addr=redis://localhost:6379"  # Point to the Redis instance              
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    release: prometheus
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9187'
    prometheus.io/path: '/metrics'
spec:
  selector:
    app: postgres
    release: prometheus
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
    - name: postgres-exporter
      port: 9187
      targetPort: 9187      
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    release: prometheus
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9121'
    prometheus.io/path: '/metrics'
spec:
  selector:
    app: redis
    release: prometheus
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
    - name: redis-exporter
      port: 9121
      targetPort: 9121      
      protocol: TCP