apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail-mtvlabk8su1
      containers:
        - name: promtail
          image: docker.io/grafana/promtail:3.0.0
          args:
            - -config.file=/etc/promtail/config.yaml
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true            
          env:
            - name: 'NAMESPACE'
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.namespace'
            - name: 'HOSTNAME' # needed when using kubernetes_sd_configs
              valueFrom:
                fieldRef:
                  fieldPath: 'spec.nodeName'                           
          volumeMounts:
          - mountPath: /etc/promtail
            name: config
          - mountPath: /run/promtail
            name: run
          - mountPath: /var/lib/docker/containers
            name: containers
            readOnly: true
          - mountPath: /var/log/pods
            name: pods
            readOnly: true
          - mountPath: /var/log/host
            name: node-logs
            readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 420
          name: promtail-config
      - hostPath:
          path: /run/promtail
          type: ""
        name: run
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: containers
      - hostPath:
          path: /var/log/pods
          type: ""
        name: pods
      - hostPath:
          path: /var/log
          type: ""
        name: node-logs
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  config.yaml: |+ 
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
      log_level: info
      log_format: logfmt

    positions:
      filename: /var/log/positions/positions.yaml
    clients:
      - url: http://loki:3100/loki/api/v1/push
    target_config:
      sync_period: 10s
    scrape_configs:
      - job_name: kubernetes-pods
        pipeline_stages:
          - cri: {}
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_controller_name
            regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
            action: replace
            target_label: __tmp_controller_name
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_name
              - __meta_kubernetes_pod_label_app
              - __tmp_controller_name
              - __meta_kubernetes_pod_name
            regex: ^;*([^;]+)(;.*)?$
            action: replace
            target_label: app
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_instance
              - __meta_kubernetes_pod_label_instance
            regex: ^;*([^;]+)(;.*)?$
            action: replace
            target_label: instance
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_component
              - __meta_kubernetes_pod_label_component
            regex: ^;*([^;]+)(;.*)?$
            action: replace
            target_label: component
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_node_name
            target_label: node_name
          - action: replace
            source_labels:
            - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            replacement: $1
            separator: /
            source_labels:
            - namespace
            - app
            target_label: job
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_container_name
            target_label: container
          - action: replace
            replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
            - __meta_kubernetes_pod_uid
            - __meta_kubernetes_pod_container_name
            target_label: __path__
          - action: replace
            regex: true/(.*)
            replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
            - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
            - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
            - __meta_kubernetes_pod_container_name
            target_label: __path__      
      - job_name: kubernetes-namespace
          kubernetes_sd_configs:
            - role: endpoints
          pipeline_stages:
            - cri: {}        
            # - json:
            #     expressions:
            #       timestamp: timestamp
            #       level: level
            #       thread: thread
            #       class: logger
            #       message: message
            #       context: context
            # - labels:
            #     level:
            #     class:
            #     context:
            #     thread:
            # - timestamp:
            #     format: RFC3339
            #     source: timestamp
            # - output:
            #     source: message            
            # - multiline:
            #     firstline: ^\x{200B}\[
            #     max_lines: 128
            #     max_wait_time: 3s
            - replace:
                expression: (\n)
                replace: ""            
          relabel_configs:
            - source_labels: [__meta_kubernetes_service_annotation_prometail_io_scrape]
              action: keep
              regex: true
            - source_labels: [__meta_kubernetes_service_label_app]
              action: replace
              target_label: job        
            - source_labels: [__meta_kubernetes_namespace]
              action: keep
              regex: mtvlabk8su1
            # - source_labels: [__meta_kubernetes_service_annotation_promtail_io_scrape]
            #   action: keep
            #   regex: "true"
            - source_labels: ['__meta_kubernetes_pod_node_name']
              target_label: '__host__'
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - source_labels: [__meta_kubernetes_namespace]
              action: replace
              target_label: namespace
            - source_labels: [__meta_kubernetes_service_name]
              action: replace
              target_label: service
            - source_labels: [__meta_kubernetes_pod_name]
              target_label: pod
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_container_name
              target_label: container
            - replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
                - __meta_kubernetes_pod_uid
                - __meta_kubernetes_pod_container_name
              target_label: __path__            
          # pipeline_stages:
          #   - cri: {}
          #   - multiline:
          #       firstline: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}'
          #       max_wait_time: 3s
          #   - regex:
          #       expression: '^(?P<date>\d{4}-\d{2}-\d{2}) (?P<time>\d{2}:\d{2}:\d{2}.\d{3}) (?P<message>(?s:.*))$$'
---
apiVersion: v1
kind: Service
metadata:
  name: promtail
spec:
  selector:
    app: promtail
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080
