{
 "title": "Redis Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Redis Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"app\") |> range(start: -1h) |> filter(fn: (r) => r._measurement == \"redis\" and r._field == \"used_memory\") |> mean()"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"app\") |> range(start: -1h) |> filter(fn: (r) => r._measurement == \"redis\" and r._field == \"clients\") |> mean()"
    }
   ]
  },
  {
   "title": "Commands Processed per Second",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"app\") |> range(start: -1h) |> filter(fn: (r) => r._measurement == \"redis\" and r._field == \"total_commands_processed\") |> derivative(unit: 1s, nonNegative: true) |> mean()"
    }
   ]
  }
 ]
}