{
 "title": "Jenkins Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Average Build Time",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Jenkins\") |> range(start: -1h) |> filter(fn: (r) => r._measurement == \"jenkins_data\" and r._field == \"build_time\") |> mean()"
    }
   ]
  },
  {
   "title": "Build Success Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Jenkins\") |> range(start: -1h) |> filter(fn: (r) => r._measurement == \"jenkins_data\" and r._field == \"build_result\") |> count()"
    }
   ]
  },
  {
   "title": "Average Queue Time",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"Jenkins\") |> range(start: -1h) |> filter(fn: (r) => r._measurement == \"jenkins_data\" and r._field == \"queue_time\") |> mean()"
    }
   ]
  },
  {
   "title": "Executor Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"Jenkins\") |> range(start: -1h) |> filter(fn: (r) => r._measurement == \"jenkins_data\" and r._field == \"executor_utilization\") |> mean()"
    }
   ]
  },
  {
   "title": "Total Build Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"Jenkins\") |> range(start: -1h) |> filter(fn: (r) => r._measurement == \"jenkins_data\" and r._field == \"total_duration\") |> mean()"
    }
   ]
  },
  {
   "title": "Successful Builds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"Jenkins\") |> range(start: -1h) |> filter(fn: (r) => r._measurement == \"jenkins_data\" and r._field == \"build_successful\") |> count()"
    }
   ]
  }
 ]
}