{
 "title": "mtvlabk8su1 - Prometheus",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Request Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Latency distribution",
   "type": "bargauge",
   "description": "Buckets in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (prometheus_http_request_duration_seconds_bucket{})",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  {
   "title": "GO GC Pause Duration ",
   "type": "bargauge",
   "description": "Summary data type - Histogram distribution",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_gc_duration_seconds{}", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Average Latency (s) / request  / handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(prometheus_http_request_duration_seconds_sum{}[5m]) / rate(prometheus_http_request_duration_seconds_count{}[5m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Average Latency (s) / request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_http_request_duration_seconds_sum[5m]))/sum(rate(prometheus_http_request_duration_seconds_count[5m]))",
     "legendFormat": "Avg Latency"
    }
   ]
  },
  {
   "title": "Average Latency / request for metrics handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(prometheus_http_request_duration_seconds_sum{handler=\"/metrics\"}[5m]) / rate(prometheus_http_request_duration_seconds_count{handler=\"/metrics\"}[5m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Percentile Distribution Histogram - Request duration seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(prometheus_http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, rate(prometheus_http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, rate(prometheus_http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.1, rate(prometheus_http_request_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Response Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Response Size Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (prometheus_http_response_size_bytes_bucket{})",
     "legendFormat": "{{le}}value"
    }
   ]
  },
  {
   "title": "Response size for 90% percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9,sum by (le) (rate(prometheus_http_response_size_bytes_bucket{}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load on Prometheus",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(prometheus_http_requests_total{}[5m]))",
     "legendFormat": "Requests/second"
    }
   ]
  },
  {
   "title": "Average Response side (bytes) / request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_http_response_size_bytes_sum[5m]))/sum(rate(prometheus_http_response_size_bytes_count[5m]))",
     "legendFormat": "Avg Latency"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections Tracker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "net_conntrack_listener_conn_accepted_total ",
       "legendFormat": "Accepted conns {{instance}}"
      }
     ]
    },
    {
     "title": "Connections Tracker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "net_conntrack_listener_conn_closed_total",
       "legendFormat": "Closed conns {{instance}}"
      }
     ]
    },
    {
     "title": "Connections Leakage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "net_conntrack_listener_conn_accepted_total ",
       "legendFormat": "Accepted conns {{instance}}"
      },
      {
       "expr": "net_conntrack_listener_conn_closed_total",
       "legendFormat": "Closed conns {{instance}}"
      }
     ]
    },
    {
     "title": "Connections Open",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "net_conntrack_listener_conn_accepted_total  - net_conntrack_listener_conn_closed_total",
       "legendFormat": "Open conns {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "process_resident_memory_bytes", "legendFormat": "Server {{instance}}" }
     ]
    }
   ]
  }
 ]
}