apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: telegraf-kubernetes
  name: telegraf-kubernetes
spec:
  serviceAccountName: telegraf-kubernetes
  serviceAccount: telegraf-kubernetes
  replicas: 1
  selector:
    matchLabels:
      app: telegraf-kubernetes
  template:
    metadata:
      labels:
        app: telegraf-kubernetes
    spec:
      containers:
      - image: telegraf:latest
        name: telegraf
        env:
          - name: INFLUX_HOST
            value: INFLUX_HOST
          - name: INFLUX_TOKEN
            value: INFLUX_TOKEN
          - name: INFLUX_ORG
            value: INFLUX_ORG
          - name: INFLUX_BUCKET
            value: INFLUX_BUCKET
        volumeMounts:
          - name: config
            mountPath: /etc/telegraf/telegraf.conf
            subPath: telegraf.conf
      volumes:
        - name: config
          configMap:
            name: telegraf-config-kubernetes            
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config-kubernetes
data:
  telegraf.conf: |
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      omit_hostname = false

    [[inputs.prometheus]]
      monitor_kubernetes_pods = true
      kubernetes_label_selector = "app=influxdb"
      metric_version = 2
      monitor_kubernetes_pods_namespace = ""
      kubernetes_services = ["https://kubernetes.default.svc.cluster.local/metrics"]
      bearer_token = "/run/secrets/kubernetes.io/serviceaccount/token"
      insecure_skip_verify = true
    [[inputs.kube_inventory]]
      url = "https://kubernetes.default"
      bearer_token = "/run/secrets/kubernetes.io/serviceaccount/token"
      namespace = ""
      insecure_skip_verify = true
      resource_exclude = []
      resource_include = []

    [[outputs.influxdb_v2]]
      urls = ["${INFLUX_HOST}"]
      token = "${INFLUX_TOKEN}"
      organization = "${INFLUX_ORG}"
      ## Destination bucket to write into.
      bucket = "${INFLUX_BUCKET}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegraf-kubernetes
  