apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-jenkins
  labels:
    app: telegraf-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf-jenkins
  template:
    metadata:
      labels:
        app: telegraf-jenkins
    spec:
      containers:
        - name: telegraf-jenkins
          image: telegraf:latest
          env:
            - name: INFLUX_HOST
              value: INFLUX_HOST
            - name: INFLUX_TOKEN
              value: INFLUX_TOKEN
            - name: INFLUX_ORG
              value: INFLUX_ORG
            - name: INFLUX_BUCKET
              value: INFLUX_BUCKET
            - name: JENKINS_HOST
              value: JENKINS_HOST
            - name: JENKINS_USERNAME
              value: JENKINS_USERNAME
            - name: JENKINS_PASSWORD
              value: JENKINS_PASSWORD
          volumeMounts:
            - name: config
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
      volumes:
        - name: config
          configMap:
            name: telegraf-config-jenkins
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config-jenkins
data:
  telegraf.conf: |
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      omit_hostname = false

    [[inputs.jenkins]]
      url = "$JENKINS_HOST"
      username = "$JENKINS_USERNAME"
      password = "$JENKINS_PASSWORD"

    [[outputs.influxdb_v2]]
      urls = ["${INFLUX_HOST}"]
      token = "${INFLUX_TOKEN}"
      organization = "${INFLUX_ORG}"
      ## Destination bucket to write into.
      bucket = "${INFLUX_BUCKET}"
