apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cache
  name: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - image: brainupgrade/observability-springboot-cache:1-influxdb
        name: observability-springboot-cache
        env:
        - name: management.metrics.export.influx.token
          value: "token"
        - name: server.port
          value: "8080"
        - name: management.metrics.export.influx.api-version
          value: "V2"
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace          
        - name: spring.application.name
          value: "$(MY_NAMESPACE)-guava-cache" 
        - name: environment
          value: "production"
        - name: management.metrics.export.influx.auto-create-db
          value: "false"
        - name: management.metrics.export.influx.bucket
          value: "springboot"
        - name: management.metrics.export.influx.org
          value: "org"
        - name: management.metrics.export.influx.uri
          value: "http://influxdb:8086"
        - name: management.endpoints.web.exposure.include
          value: "*"
        - name: management.metrics.web.server.request.autotime.enabled
          value: "true"
        - name: management.metrics.tags.application
          value: "$(MY_NAMESPACE)-guava-cache"          