apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: obs-springboot
    release: prometheus
  name: obs-springboot
spec:
  endpoints:
  - path: '/actuator/prometheus'
    port: metrics
  namespaceSelector:
    matchNames:
    - default    
  selector:
    matchLabels:
      release: prometheus
      app: obs-springboot