apiVersion: v1
kind: Service
metadata:
  name: redis-prometheus
  labels:
    app: redis
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '15692'
    prometheus.io/path: '/metrics'
spec:
  ports:
  - name: metrics
    port: 80
    targetPort: 15692
  selector:
    app: redis