apiVersion: v1
kind: Service
metadata:
  name: observability-springboot-rabbitmq-prometheus
  labels:
    app: observability-springboot-rabbitmq
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'
    prometheus.io/path: '/actuator/prometheus/'
spec:
  ports:
  - name: metrics
    port: 80
    targetPort: 8080
  selector:
    app: observability-springboot-rabbitmq                                                                
