apiVersion: v1
kind: Service
metadata:
  name: jenkins-prometheus
  labels:
    app: jenkins
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'
    prometheus.io/path: '/prometheus/'
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
  selector:
    app: jenkins                                                                                          
