apiVersion: v1
kind: Service
metadata:
  name: mariadb-exporter-prometheus
  labels:
    app: mariadb
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9104'
    prometheus.io/path: '/metrics'
spec:
  ports:
  - name: metrics
    port: 9104
    targetPort: 9104
  selector:
    app: mariadb