apiVersion: v1
kind: Service
metadata:
  name: weather-prometheus
  labels:
    app: weather
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8888'
    prometheus.io/path: '/actuator/prometheus/'
spec:
  ports:
  - name: metrics
    port: 8888
    targetPort: 8888
  selector:
    app: weather                                                                                          
