apiVersion: v1
kind: Service
metadata:
  name: node-exporter-prometheus
  labels:
    app: node-exporter
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9100'
    prometheus.io/path: '/metrics'
spec:
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
  selector:
    app: ubuntu-obs