apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  type: ClusterIP
  ports:
    - name: mariadb
      port: 3306
      targetPort: 3306
    - name: exporter
      port: 9104
      targetPort: 9104      
  selector:
    app: mariadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      volumes:
      - name: opt
        emptyDir: {}
      initContainers:
      - name: mysqlexporter
        image: brainupgrade/tshoot
        command: ['bash', '-c', 'cd /opt && wget https://github.com/prometheus/mysqld_exporter/releases/download/v0.16.0/mysqld_exporter-0.16.0.linux-amd64.tar.gz']
        volumeMounts:
        - name: opt
          mountPath: /opt
      containers:
      - image: mariadb:10.3
        name: mariadb
        volumeMounts:
        - name: opt
          mountPath: /opt
        resources: 
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 128Mi         
        ports:
        - containerPort: 3306
          name: mariadb
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
          - name: MYSQL_DATABASE
            value: prometheus
          - name: MYSQL_USER
            value: user
          - name: MYSQL_PASSWORD
            value: password